version: '3.8'

services:
  aidebate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - PORT=8000
    # No volume mount for logs - logs will be stored in the container
    restart: unless-stopped
    command: python -c "import os; port = int(os.environ.get('PORT', 8000)); import uvicorn; uvicorn.run('app.main:app', host='0.0.0.0', port=port)"
