[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ADMIN_USERNAME = { default = "admin" }
ADMIN_PASSWORD = { default = "debate123" }
